from sqlalchemy.orm import Session

from .models import Exercise

# (name, muscle_group, equipment, default rest seconds)
# Kept in sync with mobile/src/local/catalog.ts (local-mode catalog). Append-only:
# local mode derives exercise ids from list position, so never remove or reorder.
BUILTIN_EXERCISES: list[tuple[str, str, str, int]] = [
    # Chest
    ("Barbell Bench Press", "chest", "barbell", 180),
    ("Incline Barbell Bench Press", "chest", "barbell", 180),
    ("Dumbbell Bench Press", "chest", "dumbbell", 150),
    ("Incline Dumbbell Press", "chest", "dumbbell", 150),
    ("Machine Chest Press", "chest", "machine", 120),
    ("Cable Fly", "chest", "cable", 90),
    ("Pec Deck", "chest", "machine", 90),
    ("Push-Up", "chest", "bodyweight", 90),
    ("Dip", "chest", "bodyweight", 150),
    # Back
    ("Deadlift", "back", "barbell", 240),
    ("Barbell Row", "back", "barbell", 180),
    ("Pull-Up", "back", "bodyweight", 150),
    ("Chin-Up", "back", "bodyweight", 150),
    ("Lat Pulldown", "back", "cable", 120),
    ("Seated Cable Row", "back", "cable", 120),
    ("Dumbbell Row", "back", "dumbbell", 120),
    ("T-Bar Row", "back", "barbell", 150),
    ("Face Pull", "back", "cable", 90),
    ("Rack Pull", "back", "barbell", 210),
    # Shoulders
    ("Overhead Press", "shoulders", "barbell", 180),
    ("Seated Dumbbell Shoulder Press", "shoulders", "dumbbell", 150),
    ("Machine Shoulder Press", "shoulders", "machine", 120),
    ("Lateral Raise", "shoulders", "dumbbell", 60),
    ("Cable Lateral Raise", "shoulders", "cable", 60),
    ("Rear Delt Fly", "shoulders", "dumbbell", 60),
    ("Upright Row", "shoulders", "barbell", 120),
    ("Arnold Press", "shoulders", "dumbbell", 150),
    # Biceps
    ("Barbell Curl", "biceps", "barbell", 90),
    ("Dumbbell Curl", "biceps", "dumbbell", 90),
    ("Hammer Curl", "biceps", "dumbbell", 90),
    ("Incline Dumbbell Curl", "biceps", "dumbbell", 90),
    ("Preacher Curl", "biceps", "machine", 90),
    ("Cable Curl", "biceps", "cable", 90),
    # Triceps
    ("Close-Grip Bench Press", "triceps", "barbell", 150),
    ("Skull Crusher", "triceps", "barbell", 120),
    ("Triceps Pushdown", "triceps", "cable", 90),
    ("Overhead Cable Extension", "triceps", "cable", 90),
    ("Dumbbell Overhead Extension", "triceps", "dumbbell", 90),
    # Quads
    ("Back Squat", "quads", "barbell", 240),
    ("Front Squat", "quads", "barbell", 210),
    ("Leg Press", "quads", "machine", 180),
    ("Hack Squat", "quads", "machine", 180),
    ("Bulgarian Split Squat", "quads", "dumbbell", 120),
    ("Leg Extension", "quads", "machine", 90),
    ("Walking Lunge", "quads", "dumbbell", 120),
    ("Goblet Squat", "quads", "dumbbell", 120),
    # Hamstrings
    ("Romanian Deadlift", "hamstrings", "barbell", 180),
    ("Lying Leg Curl", "hamstrings", "machine", 90),
    ("Seated Leg Curl", "hamstrings", "machine", 90),
    ("Good Morning", "hamstrings", "barbell", 150),
    ("Nordic Curl", "hamstrings", "bodyweight", 120),
    # Glutes
    ("Hip Thrust", "glutes", "barbell", 150),
    ("Glute Kickback", "glutes", "cable", 90),
    ("Sumo Deadlift", "glutes", "barbell", 240),
    # Calves
    ("Standing Calf Raise", "calves", "machine", 60),
    ("Seated Calf Raise", "calves", "machine", 60),
    # Core
    ("Plank", "core", "bodyweight", 60),
    ("Hanging Leg Raise", "core", "bodyweight", 90),
    ("Cable Crunch", "core", "cable", 90),
    ("Ab Wheel Rollout", "core", "bodyweight", 90),
    ("Russian Twist", "core", "bodyweight", 60),
    # --- v1.3 catalog expansion (append-only below this line) ---
    # Chest
    ("Decline Barbell Bench Press", "chest", "barbell", 180),
    ("Barbell Floor Press", "chest", "barbell", 150),
    ("Decline Dumbbell Press", "chest", "dumbbell", 150),
    ("Dumbbell Fly", "chest", "dumbbell", 90),
    ("Incline Dumbbell Fly", "chest", "dumbbell", 90),
    ("Dumbbell Pullover", "chest", "dumbbell", 120),
    ("Smith Machine Bench Press", "chest", "smith machine", 150),
    ("Smith Machine Incline Press", "chest", "smith machine", 150),
    ("Incline Machine Chest Press", "chest", "machine", 120),
    ("Incline Cable Fly", "chest", "cable", 90),
    ("Low Cable Fly", "chest", "cable", 90),
    ("Cable Crossover", "chest", "cable", 90),
    ("Machine Fly", "chest", "machine", 90),
    ("Weighted Dip", "chest", "bodyweight", 180),
    ("Weighted Push-Up", "chest", "bodyweight", 90),
    ("Decline Push-Up", "chest", "bodyweight", 90),
    ("Deficit Push-Up", "chest", "bodyweight", 90),
    ("Band Chest Press", "chest", "band", 90),
    ("Svend Press", "chest", "plate", 60),
    # Back
    ("Trap Bar Deadlift", "back", "trap bar", 240),
    ("Deficit Deadlift", "back", "barbell", 240),
    ("Block Pull", "back", "barbell", 210),
    ("Snatch-Grip Deadlift", "back", "barbell", 240),
    ("Pendlay Row", "back", "barbell", 180),
    ("Seal Row", "back", "barbell", 150),
    ("Meadows Row", "back", "barbell", 120),
    ("Chest-Supported Row", "back", "machine", 120),
    ("Machine Row", "back", "machine", 120),
    ("Smith Machine Row", "back", "smith machine", 150),
    ("Inverted Row", "back", "bodyweight", 120),
    ("Renegade Row", "back", "dumbbell", 90),
    ("Kroc Row", "back", "dumbbell", 120),
    ("Single-Arm Cable Row", "back", "cable", 90),
    ("Wide-Grip Seated Cable Row", "back", "cable", 120),
    ("Weighted Pull-Up", "back", "bodyweight", 180),
    ("Weighted Chin-Up", "back", "bodyweight", 180),
    ("Neutral-Grip Pull-Up", "back", "bodyweight", 150),
    ("Assisted Pull-Up", "back", "machine", 120),
    ("Close-Grip Lat Pulldown", "back", "cable", 120),
    ("Wide-Grip Lat Pulldown", "back", "cable", 120),
    ("Single-Arm Lat Pulldown", "back", "cable", 90),
    ("Machine Lat Pulldown", "back", "machine", 120),
    ("Straight-Arm Pulldown", "back", "cable", 90),
    ("Machine Pullover", "back", "machine", 90),
    ("Back Extension", "back", "bodyweight", 90),
    ("45-Degree Back Extension", "back", "bodyweight", 90),
    ("Reverse Hyperextension", "back", "machine", 90),
    ("Barbell Shrug", "back", "barbell", 90),
    ("Dumbbell Shrug", "back", "dumbbell", 90),
    ("Trap Bar Shrug", "back", "trap bar", 90),
    ("Cable Shrug", "back", "cable", 90),
    # Shoulders
    ("Push Press", "shoulders", "barbell", 180),
    ("Seated Barbell Shoulder Press", "shoulders", "barbell", 180),
    ("Behind-the-Neck Press", "shoulders", "barbell", 150),
    ("Z Press", "shoulders", "barbell", 150),
    ("Standing Dumbbell Shoulder Press", "shoulders", "dumbbell", 150),
    ("Smith Machine Shoulder Press", "shoulders", "smith machine", 150),
    ("Landmine Press", "shoulders", "barbell", 120),
    ("Machine Lateral Raise", "shoulders", "machine", 60),
    ("Leaning Cable Lateral Raise", "shoulders", "cable", 60),
    ("Front Raise", "shoulders", "dumbbell", 60),
    ("Plate Front Raise", "shoulders", "plate", 60),
    ("Cable Front Raise", "shoulders", "cable", 60),
    ("Reverse Pec Deck", "shoulders", "machine", 60),
    ("Cable Rear Delt Fly", "shoulders", "cable", 60),
    ("Chest-Supported Rear Delt Row", "shoulders", "dumbbell", 90),
    ("Cable Upright Row", "shoulders", "cable", 90),
    ("Dumbbell Upright Row", "shoulders", "dumbbell", 90),
    ("Band Pull-Apart", "shoulders", "band", 60),
    ("Pike Push-Up", "shoulders", "bodyweight", 90),
    ("Handstand Push-Up", "shoulders", "bodyweight", 150),
    ("Bus Driver", "shoulders", "plate", 60),
    # Biceps
    ("EZ-Bar Curl", "biceps", "ez bar", 90),
    ("EZ-Bar Preacher Curl", "biceps", "ez bar", 90),
    ("Concentration Curl", "biceps", "dumbbell", 60),
    ("Spider Curl", "biceps", "dumbbell", 90),
    ("Zottman Curl", "biceps", "dumbbell", 90),
    ("Cross-Body Hammer Curl", "biceps", "dumbbell", 90),
    ("Rope Hammer Curl", "biceps", "cable", 90),
    ("Bayesian Curl", "biceps", "cable", 90),
    ("High Cable Curl", "biceps", "cable", 60),
    ("Machine Bicep Curl", "biceps", "machine", 90),
    ("Drag Curl", "biceps", "barbell", 90),
    ("Cheat Curl", "biceps", "barbell", 120),
    ("Band Curl", "biceps", "band", 60),
    # Triceps
    ("EZ-Bar Skull Crusher", "triceps", "ez bar", 120),
    ("Dumbbell Skull Crusher", "triceps", "dumbbell", 120),
    ("JM Press", "triceps", "barbell", 150),
    ("Rope Pushdown", "triceps", "cable", 90),
    ("Single-Arm Pushdown", "triceps", "cable", 60),
    ("Cable Overhead Triceps Extension", "triceps", "cable", 90),
    ("Machine Triceps Extension", "triceps", "machine", 90),
    ("Machine Dip", "triceps", "machine", 120),
    ("Assisted Dip", "triceps", "machine", 120),
    ("Bench Dip", "triceps", "bodyweight", 90),
    ("Diamond Push-Up", "triceps", "bodyweight", 90),
    ("Triceps Kickback", "triceps", "dumbbell", 60),
    ("Board Press", "triceps", "barbell", 180),
    # Forearms
    ("Wrist Curl", "forearms", "barbell", 60),
    ("Reverse Wrist Curl", "forearms", "barbell", 60),
    ("Dumbbell Wrist Curl", "forearms", "dumbbell", 60),
    ("Reverse Curl", "forearms", "ez bar", 90),
    ("Behind-the-Back Wrist Curl", "forearms", "barbell", 60),
    ("Farmer's Walk", "forearms", "dumbbell", 120),
    ("Plate Pinch Hold", "forearms", "plate", 90),
    ("Dead Hang", "forearms", "bodyweight", 90),
    ("Wrist Roller", "forearms", "other", 90),
    # Quads
    ("Box Squat", "quads", "barbell", 210),
    ("Pause Squat", "quads", "barbell", 210),
    ("Safety Bar Squat", "quads", "barbell", 210),
    ("Zercher Squat", "quads", "barbell", 180),
    ("Overhead Squat", "quads", "barbell", 180),
    ("Smith Machine Squat", "quads", "smith machine", 180),
    ("Belt Squat", "quads", "machine", 180),
    ("Pendulum Squat", "quads", "machine", 180),
    ("Single-Leg Leg Press", "quads", "machine", 120),
    ("Single-Leg Extension", "quads", "machine", 90),
    ("Reverse Lunge", "quads", "dumbbell", 120),
    ("Barbell Lunge", "quads", "barbell", 150),
    ("Lateral Lunge", "quads", "dumbbell", 120),
    ("Step-Up", "quads", "dumbbell", 120),
    ("Bodyweight Squat", "quads", "bodyweight", 60),
    ("Jump Squat", "quads", "bodyweight", 90),
    ("Pistol Squat", "quads", "bodyweight", 120),
    ("Sissy Squat", "quads", "bodyweight", 90),
    ("Wall Sit", "quads", "bodyweight", 60),
    ("Spanish Squat", "quads", "band", 90),
    # Hamstrings
    ("Stiff-Leg Deadlift", "hamstrings", "barbell", 180),
    ("Dumbbell Romanian Deadlift", "hamstrings", "dumbbell", 150),
    ("Single-Leg Romanian Deadlift", "hamstrings", "dumbbell", 120),
    ("Standing Leg Curl", "hamstrings", "machine", 90),
    ("Glute-Ham Raise", "hamstrings", "machine", 120),
    ("Razor Curl", "hamstrings", "bodyweight", 120),
    ("Seated Good Morning", "hamstrings", "barbell", 150),
    ("Banded Leg Curl", "hamstrings", "band", 60),
    # Glutes
    ("Machine Hip Thrust", "glutes", "machine", 150),
    ("Single-Leg Hip Thrust", "glutes", "bodyweight", 90),
    ("Glute Bridge", "glutes", "bodyweight", 60),
    ("Barbell Glute Bridge", "glutes", "barbell", 120),
    ("Frog Pump", "glutes", "bodyweight", 60),
    ("Cable Pull-Through", "glutes", "cable", 90),
    ("Machine Glute Kickback", "glutes", "machine", 90),
    ("Hip Abduction", "glutes", "machine", 60),
    ("Hip Adduction", "glutes", "machine", 60),
    ("Cable Hip Abduction", "glutes", "cable", 60),
    ("Curtsy Lunge", "glutes", "dumbbell", 90),
    ("Kettlebell Swing", "glutes", "kettlebell", 90),
    ("Lateral Band Walk", "glutes", "band", 60),
    ("Clamshell", "glutes", "band", 60),
    ("Donkey Kick", "glutes", "bodyweight", 60),
    # Calves
    ("Leg Press Calf Raise", "calves", "machine", 60),
    ("Smith Machine Calf Raise", "calves", "smith machine", 60),
    ("Single-Leg Calf Raise", "calves", "bodyweight", 60),
    ("Donkey Calf Raise", "calves", "machine", 60),
    ("Standing Barbell Calf Raise", "calves", "barbell", 60),
    ("Tibialis Raise", "calves", "bodyweight", 60),
    # Core
    ("Side Plank", "core", "bodyweight", 60),
    ("Weighted Plank", "core", "bodyweight", 60),
    ("Hanging Knee Raise", "core", "bodyweight", 60),
    ("Toes-to-Bar", "core", "bodyweight", 90),
    ("Captain's Chair Leg Raise", "core", "machine", 60),
    ("Lying Leg Raise", "core", "bodyweight", 60),
    ("Crunch", "core", "bodyweight", 60),
    ("Weighted Crunch", "core", "plate", 60),
    ("Bicycle Crunch", "core", "bodyweight", 60),
    ("Machine Crunch", "core", "machine", 60),
    ("Sit-Up", "core", "bodyweight", 60),
    ("Decline Sit-Up", "core", "bodyweight", 90),
    ("V-Up", "core", "bodyweight", 60),
    ("Dead Bug", "core", "bodyweight", 60),
    ("Mountain Climber", "core", "bodyweight", 60),
    ("Cable Woodchopper", "core", "cable", 60),
    ("Pallof Press", "core", "cable", 60),
    ("Dragon Flag", "core", "bodyweight", 120),
    ("L-Sit", "core", "bodyweight", 90),
    ("Suitcase Carry", "core", "dumbbell", 90),
    ("Copenhagen Plank", "core", "bodyweight", 60),
    ("Ab Rollout (Barbell)", "core", "barbell", 90),
    # Full body / olympic
    ("Power Clean", "full body", "barbell", 210),
    ("Hang Clean", "full body", "barbell", 180),
    ("Clean and Jerk", "full body", "barbell", 240),
    ("Clean and Press", "full body", "barbell", 210),
    ("Snatch", "full body", "barbell", 240),
    ("Power Snatch", "full body", "barbell", 210),
    ("Thruster", "full body", "barbell", 150),
    ("Kettlebell Clean and Press", "full body", "kettlebell", 120),
    ("Turkish Get-Up", "full body", "kettlebell", 120),
    ("Burpee", "full body", "bodyweight", 90),
    ("Sled Push", "full body", "other", 150),
    ("Sled Pull", "full body", "other", 150),
    ("Medicine Ball Slam", "full body", "other", 60),
    ("Wall Ball", "full body", "other", 90),
]


def seed_exercises(db: Session) -> int:
    """Insert built-in exercises that don't exist yet. Returns number inserted."""
    existing = {
        name for (name,) in db.query(Exercise.name).filter(Exercise.is_custom.is_(False)).all()
    }
    inserted = 0
    for name, muscle_group, equipment, rest in BUILTIN_EXERCISES:
        if name in existing:
            continue
        db.add(
            Exercise(
                name=name,
                muscle_group=muscle_group,
                equipment=equipment,
                rest_seconds_default=rest,
                is_custom=False,
            )
        )
        inserted += 1
    db.commit()
    return inserted
